/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_mrdonut_matrix_nativebridge_NativeMatrix */

#ifndef _Included_com_mrdonut_matrix_nativebridge_NativeMatrix
#define _Included_com_mrdonut_matrix_nativebridge_NativeMatrix
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_mrdonut_matrix_nativebridge_NativeMatrix
 * Method:    matrixaddition
 * Signature: ([[I[[I)[[I
 */
JNIEXPORT jobjectArray JNICALL Java_com_mrdonut_matrix_nativebridge_NativeMatrix_matrixAddition
  (JNIEnv *, jobject, jobjectArray, jobjectArray);

/*
 * Class:     com_mrdonut_matrix_nativebridge_NativeMatrix
 * Method:    matrixsubtraction
 * Signature: ([[I[[I)[[I
 */
JNIEXPORT jobjectArray JNICALL Java_com_mrdonut_matrix_nativebridge_NativeMatrix_matrixSubtraction
  (JNIEnv *, jobject, jobjectArray, jobjectArray);

/*
 * Class:     com_mrdonut_matrix_nativebridge_NativeMatrix
 * Method:    matrixMultiplication
 * Signature: ([[I[[I)[[I
 */
JNIEXPORT jobjectArray JNICALL Java_com_mrdonut_matrix_nativebridge_NativeMatrix_matrixMultiplication
  (JNIEnv *, jobject, jobjectArray, jobjectArray);

/*
 * Class:     com_mrdonut_matrix_nativebridge_NativeMatrix
 * Method:    scalarMultiplication
 * Signature: ([[II)[[I
 */
JNIEXPORT jobjectArray JNICALL Java_com_mrdonut_matrix_nativebridge_NativeMatrix_scalarMultiplication
  (JNIEnv *, jobject, jobjectArray, jint);

/*
 * Class:     com_mrdonut_matrix_nativebridge_NativeMatrix
 * Method:    transposeMatrix
 * Signature: ([[I)[[I
 */
JNIEXPORT jobjectArray JNICALL Java_com_mrdonut_matrix_nativebridge_NativeMatrix_transposeMatrix
  (JNIEnv *, jobject, jobjectArray);

#ifdef __cplusplus
}
#endif
#endif
